# **K-nearest Neighbors**

KNN là một trong những thuật toán supervised-learning đơn giản nhất trong ML. Khi training, thuật toán này không học được gì từ dữ liệu training, mọi tính toán được thực hiện khi nó cần dự đoán kết quả của dữ liệu mới. KNN còn được gọi là một thuật toán Instance-based hay Memory-based learning.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

In [2]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print(f'Number of classes: {len(np.unique(iris_y))}')
print(f'Number of data points: {len(iris_y)}')


X0 = iris_X[iris_y == 0,:]
print('\nSamples from class 0:\n', X0[:5,:])

X1 = iris_X[iris_y == 1,:]
print('\nSamples from class 1:\n', X1[:5,:])

X2 = iris_X[iris_y == 2,:]
print('\nSamples from class 2:\n', X2[:5,:])

Number of classes: 3
Number of data points: 150

Samples from class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Samples from class 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

Samples from class 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


Nếu nhìn vào vài dữ liệu mẫu, chúng ta thấy rằng hai cột cuối mang khá nhiều thông tin giúp chúng ta có thể phân biệt được chúng. Chúng ta dự đoán rằng kết quả classification cho cơ sở dữ liệu này sẽ tương đối cao

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
     iris_X, iris_y, test_size=50)

print('Training size:', len(y_train))
print(f'Test size: {len(y_test)}')

Training size: 100
Test size: 50


**Lấy ví dụ K=1**

In [18]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 1, p = 2)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print('Print results for 20 test data points:')
print('Predicted labels: ', y_pred[20:40])
print('Ground truth    : ', y_test[20:40])

Print results for 20 test data points:
Predicted labels:  [2 1 0 1 2 1 1 0 2 2 0 2 0 1 0 1 1 1 1 1]
Ground truth    :  [2 1 0 1 2 1 1 0 2 2 0 2 0 1 0 1 1 1 2 1]


**Phương pháp đánh giá (evaluation method)**

In [21]:
from sklearn.metrics import accuracy_score
print(f'Accuracy of 1NN: {100*accuracy_score(y_test, y_pred):.2f}%')

Accuracy of 1NN: 96.00%


In [22]:
#Thử lên K = 10
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(f'Accuracy of 10NN with major voting: {100*accuracy_score(y_test, y_pred):.2f}%')
#

Accuracy of 10NN with major voting: 98.00%


**Đánh trọng số cho các điểm lân cận**

In [28]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = 'distance')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[20:50])
print(y_test[20:50])
print(f'Accuracy of 10NN (1/distance weights): {100*accuracy_score(y_test, y_pred):.2f}%')

[2 1 0 1 2 1 1 0 2 2 0 2 0 1 0 1 1 1 2 1 1 1 1 1 2 1 0 0 2 2]
[2 1 0 1 2 1 1 0 2 2 0 2 0 1 0 1 1 1 2 1 1 1 1 1 2 2 0 0 2 2]
Accuracy of 10NN (1/distance weights): 98.00%


**Uư điểm của KNN**:



*   Độ phức tạp tính toán trong quá trình training bằng 0.
*   Việc dự đoán kết quả của dữ liệu mới rất đơn giản.
* Không cần giả sử về phân phối của các class.

**Nhược điểm của KNN:**
* KNN rất nhạy với nhiễu khi K nhỏ.
* Việc tính khoảng cách tới từng điểm dữ liệu trong training set sẽ tốn rất nhiều thời gian, đặc biệt là với các cơ sở dữ liệu có số chiều lớn và có nhiều điểm dữ liệu. Với K càng lớn thì độ phức tạp cũng sẽ tăng lên. Ngoài ra, việc lưu toàn bộ dữ liệu trong bộ nhớ cũng ảnh hưởng tới hiệu năng của KNN.




